View("UserInterfaceView",{BALANCE_CLICK:"balanceClick",WIN_MONEY_ANIMATED:"winMoneyAnimated"},function(){function h(){var a=GameSettings.getInstance();this._maskedView=new CanvasView("MaskedView");this._maskedViewContext=this._maskedView.getContext2D();this.addChild(this._maskedView);this._maskedView.setZIndex(2);this._maskedView.setPosition(151+a.reelCoordX,66+a.reelCoordY);this._maskedView.setSize(a.numReels*a.reelWidth+(a.numReels-1)*a.reelSpacing,a.reelHeight)}function f(a){var c=GameSettings.getInstance();
a=c.waysCells[a];this._maskedViewContext.globalAlpha=0.75;this._maskedViewContext.clearRect(0,0,c.numReels*c.reelWidth+(c.numReels-1)*c.reelSpacing,c.reelHeight);for(var d=0;d<a.length-1;d+=2)this._maskedViewContext.fillRect(a[d]*c.reelWidth+a[d]*c.reelSpacing,a[d+1]*c.imageHeight,c.reelWidth,c.imageHeight)}function g(){var a=new Date,c=a.getHours()+":";10>a.getMinutes()&&(c+="0");c+=a.getMinutes();this._time.setText(c)}return{init:function(a){function c(){b.portraitGambleButton.setScale(1,1);b.spinButton.setScale(1,
1);b.collectButton.setScale(1,1);b.stopAutoplayButton.setScale(1,1);if(b._window.height()>b._window.width()){b.isInPortraitMode=!0;var a=(720-Device.topOffset)*Device.scale,c=$("#Game"),a=c.height()*Device.scale,c=c.position().top,d=b._window.height()-a-c;b.portraitGambleButton.y(755);b.spinButton.visible(b.shouldShowSpinButtonInPortrait);b.spinButton.removeClass("button");b.spinButton.addClass("buttonInPortrait");b.spinButton.setPosition(473,1030);b.collectButton.removeClass("button");b.collectButton.addClass("buttonInPortrait");
b.collectButton.setPosition(473,1030);b.stopAutoplayButton.removeClass("button");b.stopAutoplayButton.addClass("buttonInPortrait");b.stopAutoplayButton.setPosition(473,1030);b.stopAutoplayButton.remainingAutoplays.addClass("portrait");b.stopAutoplayButton.remainingAutoplays.setPosition(144,151);var c=parseInt(b.spinButton._containerDiv.css("height")),a=parseInt(b.portraitGambleButton._containerDiv.css("height")),e=(d-111*Device.scale)/(a*Device.scale+c*Device.scale);1>e&&(b.spinButton.setScale(e,
e),b.collectButton.setScale(e,e),b.stopAutoplayButton.setScale(e,e),b.portraitGambleButton.setScale(e,e),d=e*a,c=755-(c-e*c)/2+d+41,b.portraitGambleButton.y(755-(a-d)/2),b.spinButton.y(c),b.collectButton.y(c),b.stopAutoplayButton.y(c));b.settingsButton.visible(!1);b.homeButton.visible(!1);b.gambleButton.visible(!1);b.portraitGambleButton.visible(b.shouldShowGambleButton);b._topButtonsBackground.visible(!0);b.topSettingsButton.visible(!0);b.topSoundButton.visible(!0);b.sideAutoplayButton.visible(!1);
b.sideSoundButton.visible(!1);b.topAutoplayButton.visible(!b.isAutoplayGame);b.paytableButton.visible(!0);b.helpButton.visible(!0);b.topHomeButton.visible(!0)}else b.isInPortraitMode=!1,b.spinButton.visible(b.shouldShowSpinButtonInLandscape),b.spinButton.removeClass("buttonInPortrait"),b.spinButton.addClass("button"),b.spinButton.setPosition(1022,219),b.collectButton.removeClass("buttonInPortrait"),b.collectButton.addClass("button"),b.collectButton.setPosition(1022,219),b.stopAutoplayButton.removeClass("buttonInPortrait"),
b.stopAutoplayButton.addClass("button"),b.stopAutoplayButton.setPosition(1022,219),b.stopAutoplayButton.remainingAutoplays.removeClass("portrait"),b.stopAutoplayButton.remainingAutoplays.setPosition(67,116),b.settingsButton.visible(!0),b.homeButton.visible(!0),b.gambleButton.visible(b.shouldShowGambleButton),b.portraitGambleButton.visible(!1),b._topButtonsBackground.visible(!1),b.topSettingsButton.visible(!1),b.topSoundButton.visible(!1),b.sideAutoplayButton.visible(!b.isAutoplayGame),b.sideSoundButton.visible(!0),
b.topAutoplayButton.visible(!1),b.paytableButton.visible(!1),b.helpButton.visible(!1),b.topHomeButton.visible(!1);b.stopButton.setSize(b.stopButton.getWidth(),b._window.height()/Device.scale)}this._super();this._config=a;this._topUIContainer;this._bottomUIContainer;this._balanceField;this._betField;this._winField;this._denominationField;this._linesView;this._winMoneyTween;this._balanceMoneyTween;this._gameNumber;this._time;this._timeTimer;this._gameTitle;this._freespinsLayer;this._topButtonsBackground;
this._maskedView;this._maskedViewContext;this.spinButton;this.stopButton;this.collectButton;this.gambleButton;this.stopAutoplayButton;this.infoLineField;this.jackpotBoxes;this.homeButton;this.settingsButton;this.paytableButton;this.denomButton;this.betButton;this.shouldShowGambleButton;this.isAutoplayGame;this.shouldShowSpinButtonInPortrait;this.shouldShowSpinButtonInLandscape;this.isInPortraitMode;this._gameTitle=new View("gameTitle"+(this._config.jackpotAllowed?"":" noJackpot"),94,616);this.addChild(new View("backgroundOverlay",
72,66));this.addChild(this._gameTitle);this._gameNumber=new TextView("gameNumberTime gameNumber","",3,60);this._time=new TextView("gameNumberTime  time","",1142,60);this.addChildren(this._gameNumber,this._time);this._topUIContainer=new View("topUIContainer",0,0);if(this._config.jackpotAllowed)this.jackpotBoxes=new JackpotBoxes(0,4,{currencyType:this._config.currencyType,currency:this._config.currency,numberOfCents:a.displayBanknotesOnly||a.noCoins?0:2}),this._topUIContainer.addChild(this.jackpotBoxes);
else{var d=new View("topGameTitle");d.setPositionType("relative");this._topUIContainer.addChild(d)}this._bottomUIContainer=new View("bottomUIContainer",96,614);this._balanceField=new MoneyTextView("textField balance",319,38,"balanceBetCurrency");this._balanceField.noCoins(a.noCoins);this._balanceField.currencyType(this._config.currencyType);this._balanceField.currency(this._config.currency);this._betField=new MoneyTextView("textField bet",632,38,"balanceBetCurrency");this._betField.noCoins(a.noCoins);
this._betField.currencyType(this._config.currencyType);this._betField.currency(this._config.currency);this._winField=new MoneyTextView("textField win",792,7,"winCurrency");this._winField.noCoins(a.noCoins);this._winField.currencyType(this._config.currencyType);this._winField.currency(this._config.currency);this._denominationField=new TextView("textField denomination","",536,47);this._denominationField.setResizeEnabled(!0);this.infoLineField=new TextView("textField infoLine","",307,5);!0==this._config.lineGame?
this._linesView=new LinesSelectView({lines:this._config.lines,currLine:this._config.currLine}):(this._linesView=new WaysToPayView({currLine:this._config.currLine,lines:this._config.lines,lineGame:this._config.lineGame,fixedLines:this._config.fixedLinesCount}),this._config.fixedLinesCount||h.call(this));this._bottomUIContainer.addChildren(this._balanceField,this._betField,this._winField,this._denominationField,this.infoLineField);d=new TextView("textLabel betTitle",this._config.betTitle,627,76);d.setResizeEnabled(!0,
137);this._bottomUIContainer.addChild(new TextView("textLabel balanceTitle",this._config.balanceTitle,323,76));this._bottomUIContainer.addChild(d);this._bottomUIContainer.addChild(new TextView("textLabel winTitle",this._config.winTitle,801,76));this.addChildren(this._topUIContainer,this._bottomUIContainer,this._linesView);this.stopButton=new Button("stopButtonOverlay",0,0);this.stopButton.setId("OverlayStopButton");this.spinButton=new Button("button spin",1022,219);this.collectButton=new Button("button collect",
1022,219);this.gambleButton=new Button("button gamble",90,219);this.portraitGambleButton=new Button("gambleButtonInPortrait",400,755);this.stopAutoplayButton=new Button("button stopAutoplay",1022,219);this.stopAutoplayButton.remainingAutoplays=new TextView("textField remainingAutoplays","",67,116);this.stopAutoplayButton.addChild(this.stopAutoplayButton.remainingAutoplays);this.denomButton=new Button("denomButtonOverlay",628,648);this.betButton=new Button("betButtonOverlay",718,648);this.homeButton=
new Button("icons home",1211+a.paddingX,100,{x:0,y:-20,width:100,height:95});d=new View("iconsImage home",8,4);d.setScale(-1,1);this.homeButton.addChild(d);this.homeButton.setScale(-1,1);this.settingsButton=new Button("icons settings",-a.paddingX,100,{x:0,y:-20,width:100,height:95});this.settingsButton.addChild(new View("iconsImage settings",8,6));this.sideSoundButton=new Button("icons sideSound",-a.paddingX,500,{x:0,y:-20,width:100,height:95});this.sideSoundImage=new View("iconsImage sideSound",
8,4);this.sideSoundImage.setScale(1,1);this.sideSoundButton.addChild(this.sideSoundImage);this.sideSoundButton.setScale(1,1);this.sideAutoplayButton=new Button("icons sideAutoplay",1211+a.paddingX,500,{x:0,y:-20,width:100,height:95});a=new View("iconsImage sideAutoplay",8,4);a.setScale(-1,1);this.sideAutoplayButton.addChild(a);this.sideAutoplayButton.setScale(-1,1);this._topButtonsBackground=new View("topButtonsBackground",0,-126);this.topSettingsButton=new Button("topIcons topSettings",96,-106);
this.paytableButton=new Button("topIcons topPaytable",234,-106);this.helpButton=new Button("topIcons topHelp",372,-106);this.topSoundButton=new Button("topIcons topSound",501,-106);this.topAutoplayButton=new Button("topIcons topAutoplay",630,-106);this.topHomeButton=new Button("topIcons topHome",1107,-106);this.addChildren(this.stopButton,this.spinButton,this.collectButton,this.gambleButton,this.stopAutoplayButton,this.homeButton,this.sideAutoplayButton,this.settingsButton,this.sideSoundButton,this._topButtonsBackground,
this.topSettingsButton,this.paytableButton,this.helpButton,this.topSoundButton,this.topAutoplayButton,this.topHomeButton,this.portraitGambleButton);this.addChildren(this.denomButton,this.betButton);this._config.fixedLinesCount||f.call(this,this._config.currLine);this._window=$(window);var b=this;setTimeout(c,0);this._window.on("resize",c);this._timeTimer=setInterval(function(){g.call(b)},1E3);g.call(this)},setGameNumber:function(a){this._gameNumber.setText(a)},getBalanceMoneyAnimating:function(){return null!=
this._balanceMoneyTween},getWinMoneyAnimating:function(){return null!=this._winMoneyTween},freespins:function(a){if(!(this._freespinsLayer&&a||!this._freespinsLayer&&!a))if(this._gameTitle.visible(!a),a){this._freespinsLayer=new View("freespinsLayer",4,4);a=new TextView("fsTextField freespinText",this._config.freespinText,3,13);a.setResizeEnabled(!0);var c=new TextView("freespinNumbers","",128,14,!1,!0);this._freespinsLayer.addChildren(a,c);this._bottomUIContainer.addChild(this._freespinsLayer);c=
a.getMeasuredHeight();a.setPosition(a.x(),(88-c)/2)}else this._bottomUIContainer.removeChild(this._freespinsLayer),this._freespinsLayer=null},balanceMoney:function(a){if(void 0==a)return this._balanceField.moneyValue();this._balanceField.moneyValue(a)},winMoney:function(a){if(void 0==a)return this._winField.moneyValue();this._winField.moneyValue(a);0==a?this._winField.visible(!1):this._winField.visible(!0)},setBet:function(a){this._betField.moneyValue(a)},setDenomination:function(a){this._config.denomination=
a;this._denominationField.setText(Utils.formatNumber(a,100,!0,this._config.noCoins));this._balanceField.denomination(a);this._winField.denomination(a);this._betField.denomination(a);null!=this.jackpotBoxes&&this.jackpotBoxes.denomination(a)},setLines:function(a){this._linesView.setLines(a);f.call(this,a)},setFixedLines:function(a){this._linesView.setFixedLines(a)},setZIndexesForSettingsShown:function(){this._topUIContainer.setZIndex(120);this._bottomUIContainer.setZIndex(120);this._gameTitle.setZIndex(121)},
setZIndexesForSettingsHidden:function(){this._topUIContainer.setZIndex(80);this._bottomUIContainer.setZIndex(80);this._gameTitle.setZIndex(81)},animateBalanceMoney:function(a,c){if(a!=this._balanceField.moneyValue())if(this._balanceMoneyTween)a<this._balanceMoneyTween.vars.balanceMoney?(this._balanceMoneyTween.kill(),this._balanceMoneyTween=null,this.balanceMoney(a),this._winMoneyTween&&this._winMoneyTween.totalTime(this._winMoneyTween.totalDuration())):this._balanceMoneyTween.updateTo({balanceMoney:a});
else{var d=this;this._balanceMoneyTween=TweenMax.to(this,c,{balanceMoney:a,ease:Linear.easeNone,onComplete:function(){d._balanceMoneyTween.kill();d._balanceMoneyTween=null}})}},animateWinMoney:function(a,c){if(a!=this._winField.moneyValue())if(this._winMoneyTween)this._winMoneyTween.updateTo({winMoney:a});else{var d=this;this._winMoneyTween=TweenMax.to(this,c,{winMoney:a,ease:Linear.easeNone,onComplete:function(){d._winMoneyTween.kill();d._winMoneyTween=null;d.dispatchEvent(new Event(UserInterfaceView.WIN_MONEY_ANIMATED))}})}},
completeAnimations:function(a,c){this._balanceMoneyTween&&a&&this._balanceMoneyTween.totalTime(this._balanceMoneyTween.totalDuration());this._winMoneyTween&&c&&this._winMoneyTween.totalTime(this._winMoneyTween.totalDuration())},updateFreespins:function(a,c){if(this._freespinsLayer){this._config.currFreespin=a;this._config.totalFreespins=c;var d=this._freespinsLayer.getChildAt(1),b="fsTextField "+GameSettings.getInstance().currLanguage;d.setText("<span class='fsTextField fsNumber'>"+a+"</span> <span class='"+
b+"'>"+this._config.ofText+"</span> <span class='fsTextField fsNumber'>"+c+"</span>");b=d.getWidth()/d.getMeasuredWidth();if(1>b){var f=d.getMeasuredHeight();d.setScale(b,b);d.setPosition(d.x(),14+(f-f*b)/2)}else d.setScale(1,1),d.setPosition(d.x(),14)}},dispose:function(){this._balanceMoneyTween&&(this._balanceMoneyTween.kill(),this._balanceMoneyTween=null);this._winMoneyTween&&(this._winMoneyTween.kill(),this._winMoneyTween=null);this._super()}}}());
