View("WinVisualizationView",{CYCLE_COMPLETE:"cycleComplete"},function(){function b(){if((this._showingLines?this._config.lines[this._lineIndex].winAmount:this._config.scatters[this._lineIndex].winAmount)&&!this._lostConnection)if(this._lineLabel.visible(!0),this._showingLines)if(this._config.lineGame)this._config.currency?this._lineLabel.setText(this._config.lineText+" "+(this._config.lines[this._lineIndex].line+1)+" - "+Utils.formatNumber(this._config.lines[this._lineIndex].winAmount,100,!0,this._config.noCoins)+
"  "+this._config.currencyType):this._lineLabel.setText(this._config.lineText+" "+(this._config.lines[this._lineIndex].line+1)+" - "+Utils.formatNumber(this._config.lines[this._lineIndex].winAmount,this._config.denomination));else{var a;a=this._config.currency?this._config.lines[this._lineIndex].count.toString()+" x "+Utils.formatNumber(this._config.lines[this._lineIndex].winPerCount,100,!0,this._config.noCoins)+" "+this._config.currencyType+" = "+Utils.formatNumber(this._config.lines[this._lineIndex].winAmount,
100,!0,this._config.noCoins)+" "+this._config.currencyType:this._config.lines[this._lineIndex].count.toString()+" x "+Utils.formatNumber(this._config.lines[this._lineIndex].winPerCount,this._config.denomination)+" = "+Utils.formatNumber(this._config.lines[this._lineIndex].winAmount,this._config.denomination);1<this._config.lines[this._lineIndex].count?this._lineLabel.setText("Combos "+a):this._lineLabel.setText("Combo "+a)}else this._config.currency?this._lineLabel.setText("Scatter - "+Utils.formatNumber(this._config.scatters[this._lineIndex].winAmount,
100,!0,this._config.noCoins)+" "+this._config.currencyType):this._lineLabel.setText("Scatter - "+Utils.formatNumber(this._config.scatters[this._lineIndex].winAmount,this._config.denomination));else this._lineLabel.visible(!1)}function c(){this._lineIndex++;var a=!1;this._showingLines&&this._lineIndex==this._config.lines.length?(this._config.scatters.length&&(this._showingLines=!1),a=!0,this._numberOfBlinks=3,this._lineIndex=0):this._showingLines||this._lineIndex!=this._config.scatters.length||(this._config.lines.length?
this._showingLines=!0:(a=!0,this._numberOfBlinks=3),this._lineIndex=0);this._config.lineGame?this._showingLines?this._linesView.drawLine(this._config.lines[this._lineIndex].cells,this._config.lines[this._lineIndex].line):this._linesView.drawCells(this._config.scatters[this._lineIndex].cells):(0==this._lineIndex?this._comboColorIndex=0:this._comboColorIndex++,this._showingLines?this._linesView.drawCells(this._config.lines[this._lineIndex].cells,this._config.comboColors[this._comboColorIndex]):this._linesView.drawCells(this._config.scatters[this._lineIndex].cells));
this._linesView.startBlinking(this._numberOfBlinks,300);b.call(this);a&&this.dispatchEvent(new Event(WinVisualizationView.CYCLE_COMPLETE))}return{init:function(a){this._config=a;this._linesView;this._showingLines;this._lineIndex;this._numberOfBlinks;this._comboColorIndex;this._timerForX2Blink;this._visibleX2;this._multiplier;this._lineLabel;this._lostConnection=!1;this._super("");this._linesView=new LinesView(this._config.linesViewConfig);this._linesView.addEventListener(LinesView.BLINKING_COMPLETE,
c,this);this._lineLabel=new TextView("textField infoLine","",400,619);this._lineLabel.setZIndex(121);this.addChildren(this._linesView,this._lineLabel)},start:function(a){if(this._config.lines.length||this._config.scatters.length)this._showingLines=this._config.scatters.length?!1:!0,this._lineIndex=this._comboColorIndex=0,this._numberOfBlinks=a?3:1,this._config.lineGame?this._showingLines?this._linesView.drawLine(this._config.lines[this._lineIndex].cells,this._config.lines[this._lineIndex].line):this._linesView.drawCells(this._config.scatters[this._lineIndex].cells):
this._showingLines?this._linesView.drawCells(this._config.lines[this._lineIndex].cells,this._config.comboColors[this._comboColorIndex]):this._linesView.drawCells(this._config.scatters[this._lineIndex].cells),this._linesView.startBlinking(this._numberOfBlinks,300),b.call(this)},stopBlinkX2:function(){this._multiplier&&(clearTimeout(this._timerForX2Blink),this._multiplier.visible(!1))},onLostConnection:function(){this._lineLabel.visible(!1);this._lostConnection=!0},dispose:function(){this._linesView.dispose();
null!=this._multiplier&&(this._multiplier.dispose(),this._multiplier=null);this._linesView.removeEventListener(LinesView.BLINKING_COMPLETE,c,this);this._lineLabel.dispose();this._super()}}}());
