ViewController("ReelsViewController",{REELS_STOPPED:"reelsStopped"},function(){function r(){for(var c=GameSettings.getInstance(),a=0;a<c.numReels;a++)if(this._reels[a].getState()==ReelView.REEL_ROTATING)return this._reels[a];return null}function w(c){if(!this._stopAllRequested&&SoundManager.getInstance().hasSound("reelAccelerateSound"))for(var a=GameSettings.getInstance(),b=a.serverMessage,d,e=a.scatterConfig.length,g=0;g<e;g++)if(d=a.scatterConfig[g],-1!=d.freespinMinCount){var h=d.index,k=a.wildIndex;
this._allowedAccelSound[h]=!1;for(var f=this._scatterCount[h]=0;f<=c;f++){var l=SpinAnalyzer.isCardOnReel(f,h,b),m=SpinAnalyzer.isCardOnReel(f,k,b);console.log("Reel "+c+" wild is "+m);if(l||m)this._scatterCount[h]++;else{this._allowedAccelSound[h]=!1;break}this._scatterCount[h]>=d.freespinMinCount-1&&(this._allowedAccelSound[h]=!0)}}}function s(c){var a=GameSettings.getInstance(),b=a.serverMessage;SoundManager.getInstance();for(var d,e,g,h=0;h<a.numReelCards;h++){d=SpinAnalyzer.getCard(c,h,b);var k=
null;e=a.scatterConfig.length;for(var f=0;f<e;f++)if(a.scatterConfig[f].index==d){k=a.scatterConfig[f];break}if(null!=k&&k.validReels[c]){var l=1;void 0!=k.maxScatterOnReel&&(l=k.maxScatterOnReel);for(f=e=g=0;f<a.numReels;f++)k.validReels[f]&&(f<c?e+=SpinAnalyzer.countCardOnReel(f,d,b):f>c&&(g+=l));if(e+g+SpinAnalyzer.countCardOnReel(c,d,b)>=k.minCount)for(e=a.scatterSounds.length,f=0;f<e;f++)if(a.scatterSounds[f].scatter==d)return f}}return-1}function n(){if(this._resultReceived){var c=r.call(this);
if(c){var a=GameSettings.getInstance();c.stop();w.call(this,c.getIndex());for(var b=!1,d=a.scatterConfig.length,e=0;e<d;e++){var g=a.scatterConfig[e];if(this._allowedAccelSound[g.index]&&g.validReels[c.getIndex()+1]){b=!0;break}}var h=this;this._stopReelTimer=window.setTimeout(function(){n.call(h)},b?1500:a.gameBetweenReelsDelay)}}else this._initialRotationTimeElapsed=!0,clearTimeout(this._stopReelTimer),this._stopReelTimer=0}function t(c){this._numReelsBounced++;c=c.target;var a=GameSettings.getInstance(),
b=SoundManager.getInstance();this._accelSoundChannel=b.stop(this._accelSoundChannel);if(!this._stopAllRequested){a:{var d=GameSettings.getInstance();if(d.stopVideos)for(var e=d.serverMessage,g=c.getIndex(),h,k,f,l=0;l<d.numReelCards;l++)if(h=SpinAnalyzer.getCard(g,l,e),d.stopVideos[h]){k=null;for(f=0;f<d.scatterConfig.length;f++)if(d.scatterConfig[f].index==h){k=d.scatterConfig[f];break}if(!k||-1!=s.call(this,g)){k=d.stopVideos[h];f=Loader.getLoader(k.src).getData();if(!f)break a;this._stopVideoPlayers[g]||
(this._stopVideoPlayers[g]=[]);var m=this._stopVideoPlayers[g][h];m||(m=new VideoPlayer(f,this._stopVideosView.getContext2D(),k),m.addEventListener(VideoPlayer.VIDEO_COMPLETE,p,this),m.addEventListener(VideoPlayer.VIDEO_READY,q,this),this._stopVideoPlayers[g][h]=m,this._numberOfStopVideos++);k=g;k={x:d.reelCoordX+k*(d.reelWidth+d.reelSpacing),y:d.reelCoordY+d.reelHeight/d.numReelCards*l,originalY:d.reelCoordY+d.reelHeight/d.numReelCards*l,row:l,col:k};this._stopVideoPlayers[g][h].addInstance(k);this._stopVideoImagesConfig[g]||
(this._stopVideoImagesConfig[g]=[]);this._stopVideoImagesConfig[g][h]=k;this._stopVideoImagesConfig[g][h].y+=this._reels[g].getDistToRest()}}}e=c.getIndex();if(this._stopVideoPlayers[e])for(d=0;d<this._stopVideoPlayers[e].length;d++)this._stopVideoPlayers[e][d]&&this._stopVideoPlayers[e][d].play()}if(this._numReelsBounced<a.numReels){e=r.call(this);g=!1;if(e)for(h=a.scatterConfig.length,d=0;d<h;d++)if(l=a.scatterConfig[d],this._allowedAccelSound[l.index]&&l.validReels[e.getIndex()]){g=!0;break}g&&
(this._accelSoundChannel=b.play("reelAccelerateSound"))}this._stopAllRequested?this._numReelsBounced==a.numReels&&b.play("stopReelAllSound"):(c=c.getIndex(),a=GameSettings.getInstance(),d=a.serverMessage,b=SoundManager.getInstance(),b.hasSound("stopWildSound")&&SpinAnalyzer.isCardOnReel(c,a.wildIndex,d)?b.play("stopWildSound"):(d=s.call(this,c),-1!=d?b.play(a.scatterSounds[d].sounds[c]):b.play("stopReelSound")))}function u(c){GameSettings.getInstance();this.getReelsRotating()||v.call(this)}function v(){var c=
GameSettings.getInstance();this._stopReelTimer&&(clearTimeout(this._stopReelTimer),this._stopReelTimer=0);for(var a=c.scatterConfig.length,b=0;b<a;b++){var d=c.scatterConfig[b];this._scatterCount[d.index]=0;this._allowedAccelSound[d.index]=!1}this._stopAllRequested=!1;this._lostConnection||this.dispatchEvent(new Event(ReelsViewController.REELS_STOPPED))}function p(c){var a;a:{c=c.target;a=GameSettings.getInstance();for(var b=0;b<a.numReels;b++)if(this._stopVideoPlayers[b])for(var d=this._stopVideoPlayers[b].length,
e=0;e<d;e++)if(this._stopVideoPlayers[b][e]==c){a=[b,e];break a}a=null}if(a){c=a[0];b=a[1];a=GameSettings.getInstance();b=this._stopVideoPlayers[c][b];for(e=0;e<a.numReelCards;e++)(d=this._stopVideoImagesConfig[c][e])&&(this._stopVideoImagesConfig[c][e]=null);b.removeEventListener(VideoPlayer.VIDEO_COMPLETE,p,this);b.removeEventListener(VideoPlayer.VIDEO_READY,q,this);b.dispose();this._numberOfStopVideos--;this._numberOfStopVideos||(this._stopVideoPlayers.length=0,this._stopVideoImagesConfig.length=
0);this.getReelsRotating()||v.call(this)}}function q(c){}return{init:function(c){this._super();this._reels;this._resultReceived;this._stopAllRequested;this._initialRotationTimeElapsed;this._stopReelTimer;this._lastTime;this._numReelsBounced;this._allowedAccelSound;this._scatterCount;this._accelSoundChannel;this._lostConnection;this._view=new View("",151,66);this._view.setSize(979,540);this._reelsView=new CanvasView("",0,0);this._reelsView.setSize(979,540);this._view.addChild(this._reelsView);this._stopVideosView=
new CanvasView("",0,0);this._stopVideosView.setSize(979,540);this._view.addChild(this._stopVideosView);var a=GameSettings.getInstance(),b=[];this._reels=[];for(var d=a.reelImages.length,e=0;e<d;e++)b[e]=Loader.getLoader(a.reelImages[e]).getData();for(e=0;e<a.numReels;e++)this._reels[e]=new ReelView({numReelImages:a.numReelCards,numImages:a.numImages,transparentReels:a.transparentReels,reelCoordX:a.reelCoordX,reelCoordY:a.reelCoordY,reelWidth:a.reelWidth,reelHeight:a.reelHeight,imageHeight:a.imageHeight,
reelSpacing:a.reelSpacing,reelImages:b,cardsInfo:a.cardsInfo,reelStartBounceTime:a.reelStartBounceTime,reelStopBounceTime:a.reelStopBounceTime,reelStopBouncePercent:a.reelStopBouncePercent,reelRotationSpeed:a.reelRotationSpeed,reelRotationDirection:a.reelRotationDirection,context:this._reelsView.getContext2D()},e),this._reels[e].setFakeReel(a.mainFakeReels[e]),this._reels[e].setResult(c,!0),this._reels[e].addEventListener(ReelView.REEL_STOPPED,u,this),this._reels[e].addEventListener(ReelView.REEL_BOUNCED,
t,this);this._scatterCount=[];this._allowedAccelSound=[];d=a.scatterConfig.length;for(e=0;e<d;e++)c=a.scatterConfig[e],this._scatterCount[c.index]=0,this._allowedAccelSound[c.index]=!1;this._stopVideoPlayers=[];this._stopVideoImagesConfig=[];this._numberOfStopVideos=0;this._initialRotationTimeElapsed=this._stopAllRequested=this._lostConnection=!1},getReelsRotating:function(){for(var c=GameSettings.getInstance(),a=0;a<c.numReels;a++)if(this._reels[a].getState()!=ReelView.REEL_IDLE)return!0;return this._stopVideoPlayers.length?
!0:!1},getStopAllRequested:function(){return this._stopAllRequested},start:function(c){if(!this.getReelsRotating()){for(var a=GameSettings.getInstance(),b=0;b<a.numReels;b++)c&&-1!=c.indexOf(b)||(this._reels[b].start(),this._numStartedReels++);if(this._stopReelTimer)throw"_stopReelTimer should be null when the reels are starting!";c=Math.max(a.gameInitialReelRotationTime,1E3*a.minimumSpinTime-((a.numReels-1)*a.gameBetweenReelsDelay+((a.numReelCards+1)*a.reelRotationSpeed+1E3*a.reelStopBounceTime)));
var d=this;this._stopReelTimer=setTimeout(function(){n.call(d)},c);this._initialRotationTimeElapsed=this._resultReceived=!1;this._numReelsBounced=0}},stopAll:function(){var c=GameSettings.getInstance();if(this.getReelsRotating()&&!(0<c.minimumSpinTime)){if(this._resultReceived)for(var a=c.reelHeight,b=0;b<c.numReels;b++)this._reels[b].stop(a);this._stopAllRequested=!0;this._stopReelTimer&&(clearTimeout(this._stopReelTimer),this._stopReelTimer=0)}},resultReceived:function(){var c=GameSettings.getInstance(),
a=c.serverMessage;if(a.type!=BaseMessage.SPIN)throw"Incorrect message type in resultReceived in ReelsViewController!";for(var b=0;b<c.numReels;b++)this._reels[b].setResult(a.reels);this._resultReceived=!0;this._stopAllRequested?this.stopAll():this._initialRotationTimeElapsed&&n.call(this)},setReels:function(c){var a=GameSettings.getInstance();if(this.getReelsRotating())throw"Cannot set reels if they are not stopped!";for(var b=0;b<a.numReels;b++)this._reels[b].setResult(c,!0)},clearReels:function(c){for(var a=
c.length,b=0;b<a;b+=2)this._reels[c[b]].clearCell(c[b+1])},setMainFakeReels:function(c){},setFreespinFakeReels:function(c){},redrawReels:function(){for(var c=GameSettings.getInstance(),a=0;a<c.numReels;a++)this._reels[a].redraw()},onLostConnection:function(){this._lostConnection=!0;this._stopReelTimer&&(clearTimeout(this._stopReelTimer),this._stopReelTimer=0)},newFrame:function(c){for(var a=GameSettings.getInstance(),b=0;b<a.numReels;b++)if(this._reels[b].draw(c),this._stopVideoImagesConfig[b])for(var d=
0;d<this._stopVideoImagesConfig[b].length;d++)if(this._stopVideoImagesConfig[b][d]){var e=this._reels[b].getDistToRest();-1!=e&&(this._stopVideoImagesConfig[b][d].y=this._stopVideoImagesConfig[b][d].originalY+e)}},dispose:function(){for(var c=this._reels.length,a=0;a<c;a++)this._reels[a].removeEventListener(ReelView.REEL_STOPPED,u,this),this._reels[a].removeEventListener(ReelView.REEL_BOUNCED,t,this),this._reels[a].dispose();this._reels=null;this._stopReelTimer&&clearTimeout(this._stopReelTimer);
c=this._stopVideoPlayers.length;for(a=0;a<c;a++)for(var b=0;b<this._stopVideoPlayers[a].length;b++)this._stopVideoPlayers[a][b].removeEventListener(VideoPlayer.VIDEO_COMPLETE,p,this),this._stopVideoPlayers[a][b].removeEventListener(VideoPlayer.VIDEO_READY,q,this),this._stopVideoPlayers[a][b].dispose();this._accelSoundChannel&&SoundManager.getInstance().stop(this._accelSoundChannel);this._stopVideoImagesConfig=this._stopVideoPlayers=null;this._super()}}}());
